#!/usr/bin/env php
<?php

use Rekhyt\PhpDependencyChecker\PhpDependencyCheckerCli;
use Rekhyt\PhpDependencyChecker\Vulnerability\Factory\PackageExclusionFileRepository;
use Rekhyt\PhpDependencyChecker\Vulnerability\Factory\VulnerabilitySLApiRepository;
use Rekhyt\PhpDependencyChecker\Vulnerability\Factory\ComposerLockFileContentFileRepository;

require_once __DIR__ . '/vendor/autoload.php';

$cli = new PhpDependencyCheckerCli(
    new VulnerabilitySLApiRepository(),
    new ComposerLockFileContentFileRepository(),
    new PackageExclusionFileRepository()
);

try {
    $cli->run();
} catch (Exception $e) {
    $cli->fatal($e);
}
