#!/usr/bin/env php
<?php
require_once __DIR__ . '/vendor/autoload.php';

$cli = new \Rekhyt\PhpDependencyChecker\PhpDependencyCheckerCli();
try {
    $cli->run();
} catch (Exception $e) {
    $cli->fatal($e);
}
