#!/usr/bin/env php
<?php
require_once __DIR__ . '/vendor/autoload.php';

$cli = new \Rekhyt\PhpDependencyChecker\PhpDependencyCheckerCli();
try {
    $cli->run();
} catch (Exception $e) {
    echo 'Unhandled Exception.'; // for the sake of completeness; should be caught by splitbrain/php-cli anyway
    exit(127);
}
